version: '3.8'

services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    devices:
      - /dev/net/tun
    cap_add:
      - MKNOD
      - NET_ADMIN
    ports:
      - "8943:943"
      - "8443:443"
      - "1194:1194/udp"
    volumes:
      - ./local/data:/openvpn
    restart: unless-stopped